export enum PresenceStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  AWAY = 'AWAY',
  BUSY = 'BUSY',
  IN_CALL = 'IN_CALL',
  RECORDING_VOICE = 'RECORDING_VOICE',
  UPLOADING = 'UPLOADING',
  WATCHING_LIVE = 'WATCHING_LIVE',
  WALKING_HOME = 'WALKING_HOME',
  INSIDE_VENUE = 'INSIDE_VENUE',
  SHARING_LOCATION = 'SHARING_LOCATION',
}

export enum CallType {
  VOICE = 'VOICE',
  VIDEO = 'VIDEO',
  GROUP_VOICE = 'GROUP_VOICE',
  GROUP_VIDEO = 'GROUP_VIDEO',
  CLUB_LOBBY = 'CLUB_LOBBY',
  NIGHTGUARD = 'NIGHTGUARD',
  BUDDY_PAIR = 'BUDDY_PAIR',
  EMERGENCY = 'EMERGENCY',
}

export enum CallState {
  REQUESTING = 'REQUESTING',
  RINGING = 'RINGING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  BUSY = 'BUSY',
  TIMEOUT = 'TIMEOUT',
  CANCELLED = 'CANCELLED',
  ENDED = 'ENDED',
  FAILED = 'FAILED',
  RECONNECTING = 'RECONNECTING',
  TRANSFERRING = 'TRANSFERRING',
}

export enum MediaState {
  MUTED = 'MUTED',
  UNMUTED = 'UNMUTED',
  CAMERA_OFF = 'CAMERA_OFF',
  CAMERA_ON = 'CAMERA_ON',
  SPEAKER_ON = 'SPEAKER_ON',
  SPEAKER_OFF = 'SPEAKER_OFF',
}

export enum DeviceType {
  ANDROID = 'ANDROID',
  IOS = 'IOS',
  WEB = 'WEB',
  UNKNOWN = 'UNKNOWN',
}

export enum DevicePriority {
  PRIMARY = 10,
  SECONDARY = 5,
  BACKGROUND = 1,
}

export enum ConnectionQuality {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  POOR = 'POOR',
  DISCONNECTED = 'DISCONNECTED',
}

export enum RoomType {
  USER = 'USER',
  CALL = 'CALL',
  GROUP = 'GROUP',
  CLUB_LOBBY = 'CLUB_LOBBY',
  NIGHTGUARD = 'NIGHTGUARD',
  PRESENCE = 'PRESENCE',
  LIVE_LOCATION = 'LIVE_LOCATION',
  CHAT = 'CHAT',
  LIVE = 'LIVE',
  MAP = 'MAP',
}

export enum NightGuardEventType {
  SOS = 'SOS',
  EMERGENCY_CALL = 'EMERGENCY_CALL',
  BUDDY_UPDATE = 'BUDDY_UPDATE',
  ETA_UPDATE = 'ETA_UPDATE',
  ARRIVAL = 'ARRIVAL',
  BATTERY_UPDATE = 'BATTERY_UPDATE',
  SAFETY_STATUS = 'SAFETY_STATUS',
  LIVE_LOCATION = 'LIVE_LOCATION',
  EMERGENCY_ACK = 'EMERGENCY_ACK',
}

export enum LiveLocationEventType {
  START = 'START',
  STOP = 'STOP',
  PAUSE = 'PAUSE',
  RESUME = 'RESUME',
  ETA_UPDATE = 'ETA_UPDATE',
  MOVEMENT = 'MOVEMENT',
  BATTERY_UPDATE = 'BATTERY_UPDATE',
  ACCURACY_UPDATE = 'ACCURACY_UPDATE',
  SESSION_END = 'SESSION_END',
  LOCATION_UPDATE = 'LOCATION_UPDATE',
}

export enum ClubLobbyEventType {
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_LEFT = 'MEMBER_LEFT',
  HOST_ANNOUNCEMENT = 'HOST_ANNOUNCEMENT',
  CROWD_COUNT = 'CROWD_COUNT',
  LIVE_CHAT = 'LIVE_CHAT',
  EVENT_COUNTDOWN = 'EVENT_COUNTDOWN',
  VENUE_ALERT = 'VENUE_ALERT',
  MODERATOR_UPDATE = 'MODERATOR_UPDATE',
  DJ_REQUEST = 'DJ_REQUEST',
  POLL_CREATED = 'POLL_CREATED',
  POLL_VOTE = 'POLL_VOTE',
}

export enum NotificationTrigger {
  INCOMING_CALL = 'INCOMING_CALL',
  MISSED_CALL = 'MISSED_CALL',
  CALL_BUSY = 'CALL_BUSY',
  CALL_REJECTED = 'CALL_REJECTED',
  GROUP_INVITATION = 'GROUP_INVITATION',
  NIGHTGUARD_ALERT = 'NIGHTGUARD_ALERT',
  EMERGENCY_ALERT = 'EMERGENCY_ALERT',
  BUDDY_PING = 'BUDDY_PING',
  SOS_TRIGGERED = 'SOS_TRIGGERED',
}

export enum ParticipantRole {
  CALLER = 'CALLER',
  CALLEE = 'CALLEE',
  PARTICIPANT = 'PARTICIPANT',
  HOST = 'HOST',
  MODERATOR = 'MODERATOR',
  VIEWER = 'VIEWER',
  BROADCASTER = 'BROADCASTER',
  GUARDIAN = 'GUARDIAN',
  OWNER = 'OWNER',
}
